// cspell:words Vous avez invité rejoindre
import { Trans } from "@lingui/react";
import { Section } from "@react-email/components";
import { EmailButton } from "../components/email-button";
import { EmailHeading } from "../components/email-heading";
import { EmailLayout } from "../components/email-layout";
import { EmailLink } from "../components/email-link";
import { EmailText } from "../components/email-text";
import { EmailIntlProvider, type SupportedLocale } from "../i18n";

export type InvitationEmailProps = {
  inviterName?: string;
  organizationName?: string;
  invitationUrl?: string;
  roles?: string[];
  expiresInDays?: number;
  locale?: SupportedLocale;
};

/**
 * Organization invitation email template.
 * Sent when an admin invites a user to join an organization.
 *
 * Note: Uses runtime Trans component with explicit IDs for Convex compatibility.
 * Message IDs generated by `lingui extract && lingui compile`.
 */
export function InvitationEmail({
  inviterName = "Admin User",
  organizationName = "Example Organization",
  invitationUrl = "https://starter-saas.fr/invitations/accept?token=example",
  roles = ["Commercial"],
  expiresInDays = 7,
  locale = "en",
}: InvitationEmailProps) {
  const rolesText = roles.join(", ");

  return (
    <EmailIntlProvider locale={locale}>
      <EmailLayout
        preview={
          locale === "fr"
            ? `Vous avez été invité à rejoindre ${organizationName}`
            : `You've been invited to join ${organizationName}`
        }
      >
        <EmailHeading>
          <Trans
            id="QaqwY/"
            message="You're invited to join {organizationName}"
            values={{ organizationName }}
          />
        </EmailHeading>
        <EmailText>
          <Trans id="VYKOAp" message="Hi there," />
        </EmailText>
        <EmailText>
          <Trans
            id="r1CXkr"
            message="{inviterName} has invited you to join {organizationName}."
            values={{ inviterName, organizationName }}
          />
        </EmailText>
        <EmailText>
          <Trans
            id="74rZ01"
            message="You've been invited with the following role(s): {rolesText}"
            values={{ rolesText }}
          />
        </EmailText>
        <Section style={buttonContainer}>
          <EmailButton href={invitationUrl}>
            <Trans id="bfXQ+N" message="Accept Invitation" />
          </EmailButton>
        </Section>
        <EmailText>
          <Trans
            id="G84Ilt"
            message="This invitation will expire in {expiresInDays} days."
            values={{ expiresInDays }}
          />
        </EmailText>
        <EmailText>
          <Trans
            id="Am7ANa"
            message="If you weren't expecting this invitation, you can safely ignore this email."
          />
        </EmailText>
        <EmailText>
          <Trans id="xNiwub" message="Or copy and paste this URL into your browser:" />{" "}
          <EmailLink href={invitationUrl}>{invitationUrl}</EmailLink>
        </EmailText>
      </EmailLayout>
    </EmailIntlProvider>
  );
}

const buttonContainer = {
  textAlign: "center" as const,
  margin: "32px 0",
};
