// cspell:words Réinitialisez votre
import { Trans } from "@lingui/react";
import { Section } from "@react-email/components";
import { EmailButton } from "../components/email-button";
import { EmailHeading } from "../components/email-heading";
import { EmailLayout } from "../components/email-layout";
import { EmailLink } from "../components/email-link";
import { EmailText } from "../components/email-text";
import { EmailIntlProvider, type SupportedLocale } from "../i18n";

export type PasswordResetEmailProps = {
  name?: string;
  resetUrl?: string;
  locale?: SupportedLocale;
};

/**
 * Password reset template.
 * Sent when a user requests to reset their password.
 *
 * Note: Uses runtime Trans component with explicit IDs for Convex compatibility.
 * Message IDs generated by `lingui extract && lingui compile`.
 */
export function PasswordResetEmail({
  name = "User",
  resetUrl = "https://starter-saas.fr/reset-password?token=example",
  locale = "en",
}: PasswordResetEmailProps) {
  return (
    <EmailIntlProvider locale={locale}>
      <EmailLayout
        preview={locale === "fr" ? "Réinitialisez votre mot de passe" : "Reset your password"}
      >
        <EmailHeading>
          <Trans id="slOprG" message="Reset your password" />
        </EmailHeading>
        <EmailText>
          <Trans id="OQHisq" message="Hi {name}," values={{ name }} />
        </EmailText>
        <EmailText>
          <Trans
            id="+bNUTW"
            message="We received a request to reset your password. Click the button below to choose a new password."
          />
        </EmailText>
        <Section style={buttonContainer}>
          <EmailButton href={resetUrl}>
            <Trans id="KbS2K9" message="Reset Password" />
          </EmailButton>
        </Section>
        <EmailText>
          <Trans
            id="0m6JtI"
            message="This link will expire in 1 hour. If you didn't request a password reset, you can safely ignore this email."
          />
        </EmailText>
        <EmailText>
          <Trans id="xNiwub" message="Or copy and paste this URL into your browser:" />{" "}
          <EmailLink href={resetUrl}>{resetUrl}</EmailLink>
        </EmailText>
      </EmailLayout>
    </EmailIntlProvider>
  );
}

const buttonContainer = {
  textAlign: "center" as const,
  margin: "32px 0",
};
