// cspell:words Vérifiez votre adresse
import { Trans } from "@lingui/react";
import { Section } from "@react-email/components";
import { EmailButton } from "../components/email-button";
import { EmailHeading } from "../components/email-heading";
import { EmailLayout } from "../components/email-layout";
import { EmailLink } from "../components/email-link";
import { EmailText } from "../components/email-text";
import { EmailIntlProvider, type SupportedLocale } from "../i18n";

export type VerificationEmailProps = {
  name?: string;
  verificationUrl?: string;
  locale?: SupportedLocale;
};

/**
 * Email verification template.
 * Sent when a user signs up and needs to verify their email.
 *
 * Note: Uses runtime Trans component with explicit IDs for Convex compatibility.
 * Message IDs generated by `lingui extract && lingui compile`.
 */
export function VerificationEmail({
  name = "User",
  verificationUrl = "https://starter-saas.fr/api/auth/verify-email?token=example",
  locale = "en",
}: VerificationEmailProps) {
  return (
    <EmailIntlProvider locale={locale}>
      <EmailLayout
        preview={locale === "fr" ? "Vérifiez votre adresse email" : "Verify your email address"}
      >
        <EmailHeading>
          <Trans id="kuvvht" message="Verify your email address" />
        </EmailHeading>
        <EmailText>
          <Trans id="OQHisq" message="Hi {name}," values={{ name }} />
        </EmailText>
        <EmailText>
          <Trans
            id="r190ll"
            message="Thanks for signing up for Starter SaaS! Please verify your email address by clicking the button below."
          />
        </EmailText>
        <Section style={buttonContainer}>
          <EmailButton href={verificationUrl}>
            <Trans id="wCKkSr" message="Verify Email" />
          </EmailButton>
        </Section>
        <EmailText>
          <Trans
            id="HNbELg"
            message="If you didn't create an account, you can safely ignore this email."
          />
        </EmailText>
        <EmailText>
          <Trans id="xNiwub" message="Or copy and paste this URL into your browser:" />{" "}
          <EmailLink href={verificationUrl}>{verificationUrl}</EmailLink>
        </EmailText>
      </EmailLayout>
    </EmailIntlProvider>
  );
}

const buttonContainer = {
  textAlign: "center" as const,
  margin: "32px 0",
};
