// cspell:words Bienvenue
import { Trans } from "@lingui/react";
import { Section } from "@react-email/components";
import { EmailButton } from "../components/email-button";
import { EmailHeading } from "../components/email-heading";
import { EmailLayout } from "../components/email-layout";
import { EmailText } from "../components/email-text";
import { colors, emailConfig, typography } from "../config";
import { EmailIntlProvider, type SupportedLocale } from "../i18n";

export type WelcomeEmailProps = {
  name?: string;
  locale?: SupportedLocale;
};

/**
 * Welcome email template.
 * Sent after a user successfully verifies their account.
 *
 * Note: Uses runtime Trans component with explicit IDs for Convex compatibility.
 * Message IDs generated by `lingui extract && lingui compile`.
 */
export function WelcomeEmail({ name = "User", locale = "en" }: WelcomeEmailProps) {
  return (
    <EmailIntlProvider locale={locale}>
      <EmailLayout
        preview={locale === "fr" ? "Bienvenue sur notre plateforme" : "Welcome to our platform"}
      >
        <EmailHeading>
          <Trans id="WUuxvV" message="Welcome!" />
        </EmailHeading>
        <EmailText>
          <Trans id="OQHisq" message="Hi {name}," values={{ name }} />
        </EmailText>
        <EmailText>
          <Trans
            id="9IbDCT"
            message="Thanks for joining us! We're excited to have you on board."
          />
        </EmailText>
        <EmailText>
          <Trans
            id="hpWU8E"
            message="Here's what you can do to get started:"
          />
        </EmailText>
        <ul style={list}>
          <li style={listItem}>
            <Trans id="g1hQ4g" message="Create and manage your tasks" />
          </li>
          <li style={listItem}>
            <Trans id="/AokE8" message="Collaborate with your team" />
          </li>
          <li style={listItem}>
            <Trans id="lRkxNV" message="Organize your work efficiently" />
          </li>
          <li style={listItem}>
            <Trans id="cQS0I1" message="Track your progress" />
          </li>
        </ul>
        <Section style={buttonContainer}>
          <EmailButton href={`${emailConfig.siteUrl}/todos`}>
            <Trans id="Y1QnKw" message="Get Started" />
          </EmailButton>
        </Section>
        <EmailText>
          <Trans
            id="+bLm+t"
            message="If you have any questions, feel free to reach out to our support team."
          />
        </EmailText>
      </EmailLayout>
    </EmailIntlProvider>
  );
}

const buttonContainer = {
  textAlign: "center" as const,
  margin: "32px 0",
};

const list = {
  color: colors.muted,
  fontSize: typography.body.fontSize,
  lineHeight: typography.body.lineHeight,
  margin: "0 0 16px",
  paddingLeft: "24px",
};

const listItem = {
  margin: "8px 0",
};
