import path from "node:path";
import { fileURLToPath } from "node:url";
import { createFeatureBoundariesZones } from "@starter-saas/eslint-config/feature-boundaries";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import";
import lingui from "eslint-plugin-lingui";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const featuresDir = path.join(__dirname, "src", "features");

// Generate feature boundary zones
const featureBoundaryZones = createFeatureBoundariesZones({
  featuresDir,
  srcPath: "./src",
  enableUnidirectional: true,
});

/**
 * ESLint config for:
 * 1. Lingui i18n rules (replaces FormatJS)
 * 2. Bulletproof React feature boundaries (import restrictions)
 *
 * Note: Biome handles all other linting (formatting, code quality, etc.)
 */
export default [
  {
    ignores: [
      ".next/**",
      ".next-e2e/**",
      "node_modules/**",
      "src/proxy.ts",
      "src/instrumentation.ts",
      // i18n message catalogs (auto-generated by Lingui)
      "**/i18n.ts",
      "src/lib/lingui.ts",
      "src/locales/*.mjs",
      // Config files with technical strings only
      "src/config/env.ts",
      // Preview auth utilities (URLs and hostnames only)
      "src/features/auth/lib/preview-auth.ts",
      // Global error boundary renders outside IntlProvider context
      // Text is intentionally hardcoded as last-resort fallback
      "src/app/global-error.tsx",
    ],
  },

  // Lingui rules for i18n
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      lingui,
    },
    rules: {
      // Detect concatenation in Trans/t that should use placeholders
      "lingui/no-expression-in-message": "error",

      // Ensure message IDs don't get out of sync
      "lingui/no-single-tag-to-translate": "error",

      // Prevent variables/expressions directly in message strings
      "lingui/no-single-variables-to-translate": "error",

      // Detect Trans components used incorrectly
      "lingui/no-trans-inside-trans": "error",

      // Ensure t`` macro is used correctly (not raw strings)
      "lingui/t-call-in-function": "error",

      // Prevent unlocalized strings
      "lingui/no-unlocalized-strings": [
        "error",
        {
          // Ignore specific attribute names (JSX props)
          ignoreNames: [
            // HTML/JSX common attributes
            "className",
            "style",
            "key",
            "id",
            // Object property names (column definitions, etc.)
            "accessorKey",
            // CSS/animation props
            "delay",
            "top",
            "width",
            "height",
            "left",
            "right",
            "bottom",
            "opacity",
            "transform",
            "transition",
            "animation",
            // Next.js Metadata (server-rendered, not i18n)
            "title",
            "description",
            "template",
            "default",
            "data-testid",
            "data-slot",
            "data-side",
            "data-align",
            "data-state",
            "type",
            "name",
            "href",
            "src",
            "alt",
            "role",
            "aria-label",
            "aria-describedby",
            "aria-labelledby",
            "placeholder",
            "autoComplete",
            "inputMode",
            "rel",
            "target",
            "method",
            "action",
            "htmlFor",
            "for",
            "encType",
            "accept",
            "slot",
            "as",
            "asChild",
            "variant",
            "size",
            "align",
            "side",
            "sideOffset",
            // Sentry/logging tags (technical identifiers)
            "actionTag",
            "feature",
            "action",
          ],
          // Ignore specific function calls (logging, utilities, etc.)
          ignoreFunctions: [
            "console.*",
            // i18n message definition functions (legacy FormatJS, migrate to Lingui)
            "defineMessages",
            "defineMessage",
            "intl.formatMessage",
            "formatMessage",
            // Error constructors
            "getConvexErrorMessage",
            "logError",
            "*.log",
            "*.warn",
            "*.error",
            "*.debug",
            // Sentry/monitoring (developer-facing messages)
            "captureMessage",
            "captureException",
            "Sentry.*",
            // URL/search params (technical strings)
            "searchParams.get",
            "URLSearchParams.get",
            "*.get",
            // Dotenv config
            "config",
            // Router navigation (URLs, not user-facing)
            "router.replace",
            "router.push",
            "redirect",
            // React Hook Form - field names are technical identifiers
            "register",
            "reset",
            "getFieldState",
            "require",
            "import",
            "cn",
            "cva",
            "clsx",
            "twMerge",
            "z.*",
            // Zod refine message properties (technical validation, not user-facing)
            "*.refine",
            "Error",
            "TypeError",
            "RangeError",
            "JSON.*",
            "Object.*",
            "Array.*",
            "String.*",
            "Number.*",
            "Boolean.*",
            "RegExp",
            "Date.*",
            "Math.*",
            "parseInt",
            "parseFloat",
            "encodeURIComponent",
            "decodeURIComponent",
            "atob",
            "btoa",
            "fetch",
            "Headers",
            "Request",
            "Response",
            "URL",
            "URLSearchParams",
            "Event",
            "CustomEvent",
            "localStorage.*",
            "sessionStorage.*",
            "document.*",
            "window.*",
            "process.env.*",
            "path.*",
            "fs.*",
          ],
          // Ignore specific string patterns (be strict - only technical strings)
          ignore: [
            // File/asset paths starting with /
            "^/assets/.*$",
            "^/images/.*$",
            "^/api/.*$",
            // Whitespace, numbers, punctuation only
            "^[\\s\\d\\W]+$",
            // CSS values (e.g., "100%", "1rem", "flex")
            "^\\d+(%|px|rem|em|vh|vw)$",
            // Tailwind CSS classes (e.g., "text-amber-600", "bg-primary")
            "^text-[a-z]+-\\d+$",
            "^(bg|text|border|ring|fill|stroke)-[a-z]+(-\\d+)?$",
            // HTTP methods
            "^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)$",
            // Boolean-like and env modes
            "^(true|false|null|undefined|development|production|test)$",
            // Sort directions
            "^(asc|desc)$",
            // Server directives
            "^use (server|client)$",
            // File extensions
            "^\\.[a-z]+$",
            // SCREAMING_SNAKE_CASE (env vars, constants)
            "^[A-Z][A-Z0-9_]+$",
            // CSS custom properties (--font-name, --color-bg)
            "^--[a-z][a-z0-9-]*$",
            // Font subsets
            "^(latin|latin-ext|cyrillic|greek|vietnamese)$",
            // Cookie sameSite values
            "^(strict|lax|none)$",
            // Log prefixes in brackets (e.g., "[Auth]", "[E2E]")
            "^\\[[A-Za-z0-9]+\\]",
            // Single lowercase word ≤8 chars (technical: "error", "warn", "debug", "default", "pending")
            "^[a-z]{1,8}$",
            // HTTP headers (e.g., "accept-language", "content-type")
            "^[a-z]+-[a-z]+(-[a-z]+)*$",
            // Auth context values (signin, signup, signout, etc.)
            "^sign(in|up|out)$",
            // UI state/variant values (connecting, connected, destructive, secondary, etc.)
            "^(connecting|connected|disconnected|loading|loaded|slow|secondary|destructive|outline|accepted|revoked|expired)$",
            // camelCase identifiers (technical tags like "googleSignIn", "authError", etc.)
            "^[a-z]+[A-Z][a-zA-Z]*$",
            // Query parameters (e.g., "?tab=members", "?view=grid")
            "^\\?[a-z]+=",
            // Sentry/log levels
            "^(warning|info|fatal|critical)$",
            // Route-like paths starting with / (including with query params)
            "^/[a-z][a-z0-9/-]*(\\?[a-zA-Z]+=[^\\s]*)?$",
            // kebab-case identifiers (technical names like "vehicle-id", "user-role")
            "^[a-z]+(-[a-z]+)+$",
            // Unicode escapes (e.g., "\u2014" em-dash, "\u2022" bullet)
            "^\\\\u[0-9a-fA-F]{4}$",
            // Single punctuation characters (em-dash, bullet, etc.)
            "^[\\u2010-\\u2027\\u2030-\\u205E]$",
            // Brand name - vroommarket (technical, not translated)
            "^vroommarket$",
            // Full URLs (technical, not translated)
            "^https?://.*$",
            // Domain patterns (vercel.app, etc.)
            "^\\.vercel\\.app$",
            // File paths with extensions (e.g., ".env.e2e")
            "^\\.env(\\.[a-z]+)?$",
            // snake_case identifiers (validation keys like "min_one_role", "invalid_email")
            "^[a-z]+(_[a-z]+)+$",
            // Agency role values (commercial, owner, etc.) - 10 chars max
            "^(commercial|owner|manager|admin|member|viewer|editor)$",
            // Form field placeholders - brand names and example values (e.g., "Toyota", "Camry", "ABC-1234")
            // Single capitalized word ≤10 chars (brand names in form examples)
            "^[A-Z][a-z]{1,9}$",
            // Example patterns (e.g., "ABC-1234", "+33 1 23 45 67 89")
            "^[A-Z]+-\\d+$",
            // Phone format patterns
            "^\\+\\d{1,3}.*$",
            // Email domain patterns (e.g., "contact@agency.com")
            "^[a-z]+@[a-z]+\\.[a-z]+$",
          ],
        },
      ],
    },
  },

  // Feature boundaries - Bulletproof React architecture
  // Enforces:
  // 1. No cross-feature imports (features/auth cannot import from features/vehicles)
  // 2. Unidirectional data flow (shared -> features -> app)
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        project: "./tsconfig.json",
      },
    },
    plugins: {
      import: importPlugin,
    },
    settings: {
      "import/resolver": {
        typescript: {
          alwaysTryTypes: true,
          project: "./tsconfig.json",
        },
      },
    },
    rules: {
      // Convex: enforce our wrapper hook (status + caching) instead of raw useQuery
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "convex/react",
              importNames: ["useQuery"],
              message: "Use `useQueryWithStatus` from `@/lib/convex-hooks` instead of `useQuery`.",
            },
            {
              name: "convex-helpers/react/cache/hooks",
              importNames: ["useQuery"],
              message: "Use `useQueryWithStatus` from `@/lib/convex-hooks` instead of `useQuery`.",
            },
          ],
        },
      ],

      // Dynamic feature boundary rules (auto-generated from features folder)
      ...(featureBoundaryZones.length > 0
        ? {
            "import/no-restricted-paths": [
              "error",
              {
                zones: featureBoundaryZones,
              },
            ],
          }
        : {}),
    },
  },
];
