# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# Validate all files (worktree doesn't support git diff mode)
VALIDATE_ALL_CODEBASE: true

# all, none, or list of linter keys
APPLY_FIXES: all

# Spell checking configuration
SPELL_CSPELL_CONFIG_FILE: "cspell.json"

# Don't block CI/CD on linter errors during transition period
DISABLE_ERRORS: true

# Exclude linters (using Biome/Ultracite for TypeScript linting instead)
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - TYPESCRIPT_STANDARD

SHOW_ELAPSED_TIME: true

# JSON linter exclusions - tsconfig.json files support comments (JSONC format)
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: "tsconfig.*\\.json$"

# Markdown - only check for critical issues
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: ".markdownlint.json"

# CSS/Stylelint - use project configuration
CSS_STYLELINT_CONFIG_FILE: LINTER_DEFAULT

# YAML validation - skip generated files
YAML_V8R_FILTER_REGEX_EXCLUDE: "(node_modules|.next|dist|build)"
