"use client";

import type { Id } from "@starter-saas/backend/convex/_generated/dataModel";
import { Avatar, AvatarFallback, AvatarImage } from "@starter-saas/ui/avatar";
import { Button } from "@starter-saas/ui/button";
import { Camera, Upload, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { useImageUpload } from "@/hooks/use-image-upload";
import { useImageUrl } from "@/hooks/use-image-url";
import { cn } from "@/lib/utils";

// Constants for file validation
const MAX_FILE_SIZE_MB = 5;
const BYTES_PER_KB = 1024;
const KB_PER_MB = 1024;
const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * BYTES_PER_KB * KB_PER_MB; // 5MB

type ImageUploadProps = {
  currentImage?: string;
  currentStorageId?: Id<"_storage">;
  onImageChange: (imageUrl: string, storageId?: Id<"_storage">, file?: File) => void;
  firstName?: string;
  lastName?: string;
  className?: string;
};

export function ImageUpload({
  currentImage,
  currentStorageId,
  onImageChange,
  firstName,
  lastName,
  className,
}: ImageUploadProps) {
  const [preview, setPreview] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { uploadImage, isUploading } = useImageUpload();

  // Get the image URL from storage ID if available
  const imageUrl = useImageUrl(currentStorageId);
  const displayImage = preview || imageUrl || currentImage || undefined;

  // Clean up preview URL when actual image URL is available
  useEffect(() => {
    if (imageUrl && preview) {
      URL.revokeObjectURL(preview);
      setPreview(null);
    }
  }, [imageUrl, preview]);

  const getInitials = (first?: string, last?: string) => {
    const firstInitial = first?.charAt(0)?.toUpperCase() || "";
    const lastInitial = last?.charAt(0)?.toUpperCase() || "";
    return firstInitial + lastInitial || "U";
  };

  const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) {
      return;
    }

    // Validate file type
    if (!file.type.startsWith("image/")) {
      toast.error("Please select an image file");
      return;
    }

    // Validate file size (5MB limit)
    if (file.size > MAX_FILE_SIZE_BYTES) {
      toast.error("File size must be less than 5MB");
      return;
    }

    // Create preview
    const previewUrl = URL.createObjectURL(file);
    setPreview(previewUrl);

    // Upload image
    const storageId = await uploadImage(file);
    if (storageId) {
      // Pass the preview URL, storage ID, and file to the callback
      // The actual URL will be generated by the useImageUrl hook
      onImageChange(previewUrl, storageId, file);
    } else {
      // Remove preview on error
      URL.revokeObjectURL(previewUrl);
      setPreview(null);
    }
  };

  const handleRemoveImage = () => {
    onImageChange("", undefined, undefined);
    setPreview(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  };

  return (
    <div className={cn("flex items-center gap-4", className)}>
      <div className="relative">
        <Avatar className="h-20 w-20">
          <AvatarImage
            alt="Profile picture"
            src={displayImage && displayImage.trim() !== "" ? displayImage : undefined}
          />
          <AvatarFallback className="text-lg">{getInitials(firstName, lastName)}</AvatarFallback>
        </Avatar>
        {isUploading && (
          <div className="absolute inset-0 flex items-center justify-center rounded-full bg-black/50">
            <div className="h-6 w-6 animate-spin rounded-full border-white border-b-2" />
          </div>
        )}
      </div>

      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Camera className="h-4 w-4 text-muted-foreground" />
          <span className="text-muted-foreground text-sm">Profile Picture</span>
        </div>

        <div className="flex gap-2">
          <Button
            className="flex items-center gap-2"
            disabled={isUploading}
            onClick={() => fileInputRef.current?.click()}
            size="sm"
            type="button"
            variant="outline"
          >
            <Upload className="h-3 w-3" />
            {currentImage ? "Change" : "Upload"}
          </Button>

          {currentImage && (
            <Button
              className="flex items-center gap-2 text-red-600 hover:text-red-700"
              disabled={isUploading}
              onClick={handleRemoveImage}
              size="sm"
              type="button"
              variant="outline"
            >
              <X className="h-3 w-3" />
              Remove
            </Button>
          )}
        </div>

        <div className="text-muted-foreground text-xs">JPG, PNG or GIF. Max 5MB.</div>
      </div>

      <input
        accept="image/*"
        className="hidden"
        onChange={handleFileSelect}
        ref={fileInputRef}
        type="file"
      />
    </div>
  );
}
