import { i18n, type Messages } from "@lingui/core";
import { I18nProvider } from "@lingui/react";
import type { SupportedLocale } from "@starter-saas/shared/i18n-types";
import type { ReactNode } from "react";
// Import compiled messages from .mjs files (generated by lingui compile)
import { messages as enMessages } from "./locales/en.mjs";
import { messages as frMessages } from "./locales/fr.mjs";

// Re-export shared locale utilities for email package consumers
export {
  getBestLocale,
  isSupportedLocale,
  SUPPORTED_LOCALES as supportedLocales,
  type SupportedLocale,
} from "@starter-saas/shared/i18n-types";

const allMessages: Record<SupportedLocale, Messages> = {
  en: enMessages,
  fr: frMessages,
};

export type EmailIntlProviderProps = {
  locale?: SupportedLocale;
  children: ReactNode;
};

/**
 * I18nProvider wrapper for email templates.
 * Wraps email content with the appropriate locale messages.
 *
 * @example
 * <EmailIntlProvider locale="fr">
 *   <EmailContent />
 * </EmailIntlProvider>
 */
export function EmailIntlProvider({ locale = "en", children }: EmailIntlProviderProps) {
  // Create a new i18n instance for each render to avoid state pollution
  i18n.load(locale, allMessages[locale]);
  i18n.activate(locale);

  return <I18nProvider i18n={i18n}>{children}</I18nProvider>;
}

// Re-export Lingui runtime components for convenience
// Note: Trans and Plural macros should be imported directly from @lingui/react/macro
// in consuming files - they cannot be re-exported (causes bundler issues with babel-plugin-macros)
export { useLingui } from "@lingui/react";
